"""tenant stripe billing fields

Revision ID: 5ff2ab439513
Revises: b6fdde10b968
Create Date: 2026-07-29 21:17:34.034238
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5ff2ab439513'
down_revision: str | None = 'b6fdde10b968'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_tenants_stripe_customer_id', 'tenants', ['stripe_customer_id'])
    op.create_unique_constraint('uq_tenants_stripe_subscription_id', 'tenants', ['stripe_subscription_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tenants_stripe_subscription_id', 'tenants', type_='unique')
    op.drop_constraint('uq_tenants_stripe_customer_id', 'tenants', type_='unique')
    op.drop_column('tenants', 'stripe_subscription_id')
    op.drop_column('tenants', 'stripe_customer_id')
    # ### end Alembic commands ###
