"""unique index on lower tenant name

Revision ID: aced294f4a1a
Revises: 4939ac2a2754
Create Date: 2026-08-10 12:45:00.801950
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'aced294f4a1a'
down_revision: str | None = '4939ac2a2754'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_tenants_name_lower', 'tenants', [sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_tenants_name_lower', table_name='tenants')
    # ### end Alembic commands ###
