"""public widget API: widget sessions

Revision ID: fd7584e7dc12
Revises: a38d45da4f68
Create Date: 2026-07-28 15:38:50.459376
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fd7584e7dc12'
down_revision: str | None = 'a38d45da4f68'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_sessions',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_widget_sessions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_widget_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_sessions'))
    )
    op.create_index(op.f('ix_widget_sessions_agent_id'), 'widget_sessions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_widget_sessions_tenant_id'), 'widget_sessions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_sessions_tenant_id'), table_name='widget_sessions')
    op.drop_index(op.f('ix_widget_sessions_agent_id'), table_name='widget_sessions')
    op.drop_table('widget_sessions')
    # ### end Alembic commands ###
